/*
 * This source file was generated by the Gradle 'init' task
 */
package org.peters;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;


class AppTest {
    ObjectMapper objectMapper = new ObjectMapper();

    @Test void nslookup()throws IOException{
      App classUnderTest = new App();
          File file = new File("src/main/resources/config.json");
          Config config = objectMapper.readValue(file, Config.class);
          String url = config.getUrl();
          String hostName = url.replace("https://","");
          String ip = classUnderTest.getIP(hostName);
          System.out.println(hostName);
          System.out.println(hostName);
          assertEquals(hostName,"www.dnsjava.org" );
          assertEquals(ip, "3.33.152.147");
     }

    @Test void jsonParseConfig() throws IOException {
        File file = new File("src/main/resources/config.json");
        Config config = objectMapper.readValue(file, Config.class);

        assertEquals(config.getUrl(),"https://www.dnsjava.org");
    }

    }

