/*
 * This source file was generated by the Gradle 'init' task
 */
package org.peters;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.*;
import java.net.*;
import java.util.*;

class AppTest {

        @Test void nslookup() {
            App classUnderTest = new App();
            try {
                String ip = classUnderTest.getIP("www.google.com");
                assertEquals(ip, "142.250.65.100");
            } catch (UnknownHostException uhe) {
                uhe.printStackTrace();
            }
        }
    }

