/*
 * This source file was generated by the Gradle 'init' task
 */
package org.peters;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.*;
import java.net.*;
import java.util.*;

class AppTest {

        @Test void appHasAGreeting() {
            App classUnderTest = new App();
           // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        }
    }

