/*
 * This source file was generated by the Gradle 'init' task
 */
package org.peters;

import java.io.*;
import java.net.*;
import java.util.*;

public class App {
    public static void main(String[] args) {
        try {
            InetAddress address = InetAddress.getByName("www.google.com");
            System.out.println("InetAddress of Named Host : " + address);
        } catch (UnknownHostException uhe) {
            uhe.printStackTrace();
        }
    }

}


