/*
 * This source file was generated by the Gradle 'init' task
 */
package org.peters;

import java.net.InetAddress;
import java.net.UnknownHostException;

public class App {


    public String getIP(String hostName) throws UnknownHostException{
        InetAddress address = InetAddress.getByName(hostName);
        System.out.println("InetAddress of Named Host : " + address);
        return address.getHostAddress();

    }

    public static void main(String[] args) {
    }


}


