/*
 * This source file was generated by the Gradle 'init' task
 */
package org.peters;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.net.*;
import java.io.*;
public class App {


    public String getIP(String hostName) throws UnknownHostException{
        InetAddress address = InetAddress.getByName(hostName);
        System.out.println("InetAddress of Named Host : " + address);
        return address.getHostAddress();

    }

    public String getPublicIP()throws UnknownHostException {
        String systemipaddress = "";
        try
        {
            URL url_name = new URL("https://api.ipify.org");
            BufferedReader sc = new BufferedReader(new InputStreamReader(url_name.openStream()));
            systemipaddress = sc.readLine().trim();
        }
        catch (Exception e)
        {
            systemipaddress = "Cannot Execute Properly";
        }
        System.out.println("Public IP Address: " + systemipaddress +"\n");
        return systemipaddress;
    }

    public App(){
        Config config = new Config();
        String url = config.getUrl();
        String host = config.getHost();
        System.out.println(url);
        System.out.println(host);
    }

    public static void main(String[] args) {
    }


}


